[WIP] 최소사항 클러스터 지원을 위한 여정
openinfradev/decapod-site pull request #174
Opened 2023-08-29 07:45 UTC by intelliguy

- Minimal deploy support

2023-08-29 08:36 UTC, ktkfree commented on eks-msa-reference/lma/site-values.yaml
> +        path: /var/log/messages
다른 커밋에 포함되었던 내용으로 보입니다.

2023-08-29 08:41 UTC, intelliguy commented on eks-msa-reference/lma/site-values.yaml
> +        path: /var/log/messages
이게 develop에 없어서 같이 들어갔네요..

2023-08-29 08:44 UTC, ktkfree commented
각각의 타입에 따라 인프라 구성이 다르고, 좀 복잡한데요..
아래의 내용으로 팀내 공유 한번하고, tks-api db scheme 작업및 로직 작업 진행하겠습니다.

정리하면,
- control plane ( 
  - aws : cpReplicas 
  - eks : N/A
  - replicas 로 개수를 조정하며, eks 는 control plane 을 dont care 하므로 N/A
- worker ( tks )
  - aws, eks ( machine pool 사용 )
    - 사용자는 tks-console 에서 "인프라 노드(1 - 3)" 의 값을 입력. 이 값이 곧 tksInfraNode 이며, tksInfraNodeMax 의 default
    - minSize : 0
    - maxSize : tksInfraNodeMax
    - replicas : tksInfraNode
    - 이 스펙에서는 replicas 로 개수를 조정함.
- worker ( user )
  - aws - machine deployment 사용
    - 사용자는 tks-console 에서 "워커 노드(1 - 100)" 의 값을 입력. 이 값이 곧 tksInfraNodeMax
    - numOfAz : ? ( 아마도 1 고정일듯 )
    - minSizePerAZ : 0
    - maxSizePerAZ : tksUserNodeMax
    - 이 스펙에는 az 설정을 고정하고, replicas 가 아닌 min. max size 로 개수를 조정함.
  - eks - machine pool 사용
    - 사용자는 tks-console 에서 "워커 노드(1 - 100)" 의 값을 입력. 이 값이 곧 tksUserNode 이며, tksUserNodeMax 의 default
    - minSize : 0
    - maxSize : tksUserNodeMax
    - replicas : tksUserNode
    - 이 스펙에서는 replicas 로 개수를 조정함.

2023-08-29 08:48 UTC, intelliguy commented
numOfAz는 존마다 다르긴한데 우리가 쓰는곳은 3일꺼에요...

2023-08-29 08:50 UTC, ktkfree commented on eks-msa-reference/lma/site-values.yaml
> +        path: /var/log/messages
네, 그 커밋은 main hotfix 후 develop merge 할 예정입니다. 이 PR 이 "여정" PR 이니 hotfix 후 천천히 rebase 하면 되겠습니다.

2023-08-29 08:57 UTC, ktkfree commented
> numOfAz는 리전마다 다르긴한데 우리가 쓰는곳은 3일꺼에요...
> 
> 저도 변경된 이름을 기준으로 workflow 수정 갑니다.

그렇다면, 현재 기준으로 machineDeployment 는 구성하기 어렵습니다. numOfAz 가 3 인 상황에 사용자가 7을 입력했다면 어떻게 spec 을 구성하면 될까요?
또한, multiAZ 지원으로 lma가 포함된 user cluster 를 생성하게 된다면 ebs region 이슈가 존재하기도 하고요.
이 부분 역시 팀 공유하며 의견을 들어보면 좋겠습니다.

2023-08-30 06:19 UTC, intelliguy commented
MachineDeploy와 MachinePool은 aws 내부적으로 동작하는 방식도 다르고 효과도 다르므로 고려는 해야겠지만...
누구나 쉽게 쓸수 있는 서비스를 구성한 다는 관점에서는 이런 제약이 있고 설명이 필요한 내역은 과감히 삭제하는 것이 좋겠다는 의견입니다.
(MchineDeploy 쓰지말자..)

2023-08-30 11:53 UTC, bluejayA requested changes
WIP 동안 merge 방지

2023-09-07 01:54 UTC, ktkfree commented on aws-msa-reference/tks-cluster/site-values.yaml
> +  tksUserNodeType: CHANGEME
@intelliguy 님.
@robertchoi80 님의 의견 ( 수 임을 알 수 있도록 변수명에 num, cnt 등 명시 ) 확인해 주시면, 이 이름으로 tks-api 도 개발 진행하겠습니다.

2023-09-11 03:51 UTC, intelliguy commented on aws-msa-reference/tks-cluster/site-values.yaml
> +  tksUserNodeType: CHANGEME
그럼 정확한 용어를 사용하시죠.
- tksInfraNodeDesired
- tksUserNodeDesried
- cpNoodeDesried

이렇게 바꿔서 다시 amend로 commit하겠습니다.

2023-09-12 01:48 UTC, ktkfree approved these changes

2023-09-12 01:49 UTC, Siyeop approved these changes
👍

2023-09-12 01:58 UTC, merged